### ISSUE TITLE
HTML Comments

### ISSUE THREAD

**Issue by p-tupe** [gennaro-tedesco/nvim-commaround#5] opened 2021-03-24 11:58 UTC
Adding  `lua require('nvim-commaround.config').config["html"] = {single = nil, block = {left = "<!--", right = "-->"}}` for styling html code throws an error.

I guess we need to wrangle single to block somehow for html filetypes.

_As an aside, would love if it was possible to comment out using motions._

Thanks for your work. Cheers!

**Comment by gennaro-tedesco** [comment] 2021-03-24 13:01
I suspect the error is due to a missing condition for single `nil`s, I will have a look later on.

> As an aside, would love if it was possible to comment out using motions.

yes, you are right. I do not exactly know how to implement operator motions with lua, but this is something I have been wanting to look into for a long time. If you have some docs or resources please feel free to share them!

**Comment by p-tupe** [comment] 2021-03-24 14:04
Yep. The error is as you surmised -

`E5108: Error executing lua ...ugged/nvim-commaround/lua/nvim-commaround/commaround.lua:7: attempt to get length of field 'single' (a nil value)`

---

I'm afraid my knowledge of lua is quite less than yours. All I can do it point to another repos

1. Contains tons of vim <-> lua functions [plenary](https://github.com/nvim-lua/plenary.nvim). 
2. Is also a comment plugin written in lua and has motions [nvim-comment](https://github.com/terrortylor/nvim-comment)

Note `Uses the built in commentstring buffer option to define comment markers`, can use this instead of adding config options for all languages.

**Comment by gennaro-tedesco** [comment] 2021-03-24 15:48
[This pull request](https://github.com/gennaro-tedesco/nvim-commaround/pull/6) should address the error for single line comments whenever they are `nil`.  Please check that all works as intended (you can install this branch of the plugin specifically and have it running).

**Comment by gennaro-tedesco** [comment] 2021-03-25 10:06
Addressed in https://github.com/gennaro-tedesco/nvim-commaround/pull/6.

Closing as we can open a new feature issue in case we want to allow for block comments to operate on single lines too.

**Closed as completed by gennaro-tedesco** 2021-03-25 10:06 UTC
Labels: bug
