### ISSUE TITLE
Single line comment support for html, xml

### ISSUE THREAD

**Issue by p-tupe** [gennaro-tedesco/nvim-commaround#8] opened 2021-03-25 10:30 UTC
Hello!

Would love if support for html, xml single line comments was present, like so -

```html
<!-- Comment goes here -->

<a href="#"> link </a>    <!-- uncommented tag --> 

<!-- <a href="#"> link </a> -->    <!-- commented tag --> 
```

Thanks!

**Comment by gennaro-tedesco** [comment] 2021-03-25 10:42
I see, so essentially we want to use the block comment characters at the beginning and end of the line, wrapping the text inside, if I understand correctly.

**Comment by gennaro-tedesco** [comment] 2021-03-25 15:40
I have created pull request https://github.com/gennaro-tedesco/nvim-commaround/pull/9 to address this issue. At a first glance it seems to me that the change is trivial, one can simply toggle block mode on single lines too, [see here](https://github.com/gennaro-tedesco/nvim-commaround/pull/9/files).

I am trying to mock the `vim.api` for testing, however this seems to be slightly non-trivial. Below you can find a gif of the expected behaviour on single lines for html files:

![Screen-Recording-2021-03-25-at-1](https://user-images.githubusercontent.com/15387611/112500548-c5e32b00-8d88-11eb-9d05-a758ee425f34.gif)

Please check that it works as expected on standard html files (both for single and for block comments again).

**Comment by p-tupe** [comment] 2021-03-26 05:31
Hello mate,

I checked the `single-wrap` branch on an html file. Works just fine, for both single and block comments.

It doesn't work for xml files though. Perhaps we can add them to the config before merge? Their comment scheme is same as html.

Thanks!

**Comment by gennaro-tedesco** [comment] 2021-03-26 10:02
I added xml configurations in ccd5a173aaeae9d06c51a25245ee98e48b2e2f3e

If all good, I will merge.

**Comment by p-tupe** [comment] 2021-03-26 14:07
Yep. all good! Can merge. Thank you!

**Comment by gennaro-tedesco** [comment] 2021-03-26 14:37
Merged. Please `PlugUpdate` to see all new changes.

**Closed as completed by gennaro-tedesco** 2021-03-26 14:37 UTC
Labels: enhancement
